Issue25 add constant refreshpolicy getrefreshpolicy return to all datasources
ascam/DOTMessage pull request #27
Opened 2023-05-15 10:22 UTC by afontquerni

2023-05-15 12:57 UTC, JosepSubirana requested changes

2023-05-15 12:57 UTC, JosepSubirana commented on src/dom/components/datasources/datetime/datecodedatetimesource.hpp
> +					RefreshPolicy GetRefreshPolicy() override { return dot::RefreshPolicy::kMinutes; } //TODO: Review
? Todo : Review

2023-05-15 12:57 UTC, JosepSubirana commented on include/dom/visitors/refreshpolicy/refreshpolicydatasourcevisitor.hpp
> +				_result |= static_cast <unsigned int>(ds.GetRefreshPolicy());
en el cas de canviar el tipus que indexa la enumeració tindrem problemes

2023-05-15 12:57 UTC, JosepSubirana commented on src/dom/components/datasources/datetime/fixedtextdatetimesource.hpp
> +					RefreshPolicy GetRefreshPolicy() override { return dot::RefreshPolicy::kNone; }
no podriem deixar aquesta part a la classe base enlloc de ser virtual pura i qui li convingui ja farà el override

2023-05-15 12:57 UTC, JosepSubirana commented on src/dom/components/datasources/datetime/secondmultiplesdatetimesource.hpp
> +					RefreshPolicy GetRefreshPolicy() override { return dot::RefreshPolicy::kSeconds; } //TODO: Review
? comentari

2023-05-16 06:55 UTC, afontquerni commented on src/dom/components/datasources/datetime/datecodedatetimesource.hpp
> +					RefreshPolicy GetRefreshPolicy() override { return dot::RefreshPolicy::kMinutes; } //TODO: Review
Aquest objecte depen entenc del contingut ('datacode') per tant pot tenir un data de codi que canvii sol l'any per exemple, i la 'policy' s'hauria de retornar aquesta. Per defecte, he posat la més exigent a nivell temporal (segons)

2023-05-16 06:57 UTC, afontquerni commented on include/dom/visitors/refreshpolicy/refreshpolicydatasourcevisitor.hpp
> +				_result |= static_cast <unsigned int>(ds.GetRefreshPolicy());
Correcte. Però la codificacio actual i la filosofia de l'enumeracio actual -pre-existent-   està feta per fer màscares (més que posicions). **Proposta ?**

2023-05-16 06:58 UTC, afontquerni commented on src/dom/components/datasources/datetime/secondmultiplesdatetimesource.hpp
> +					RefreshPolicy GetRefreshPolicy() override { return dot::RefreshPolicy::kSeconds; } //TODO: Review
Ara mateix esta definida la classe pero té una implementació parcial i no es fa servir

2023-05-16 07:08 UTC, afontquerni commented on src/dom/components/datasources/datetime/fixedtextdatetimesource.hpp
> +					RefreshPolicy GetRefreshPolicy() override { return dot::RefreshPolicy::kNone; }
He preferit deixar-ho així per aflorar totes els classe derivades que s'havia d'afegir aquest nou mètode i  'obligar' al desenvolupador que heredi la base 'DateTimeSource'.

També crec que és part essencial de la classe derivada aquest mètode per saber la seva propietat temporal pròpia i cal assegurar la seva implementació especifica en cada classe més que tenir un valor per defecte en la base (o classe pare)

2023-05-16 09:50 UTC, JosepSubirana approved these changes

2023-05-16 10:57 UTC, merged