Issue6 reorganize repository
ascam/DOTMessage pull request #7
Opened 2023-02-28 16:48 UTC by iserramacsa

2023-03-02 11:28 UTC, JosepSubirana approved these changes

2023-03-03 08:45 UTC, AlexMacsa requested changes

2023-03-03 08:45 UTC, AlexMacsa commented on src/visitors/nisx/nisxwriter.cpp
> +}
```suggestion
static constexpr const char* kSupportedNisxVersion = "1.3";

std::string NisxWriter::GetWriterNisxVersion()
{
	return kSupportedNisxVersion;
}
```

2023-03-03 08:45 UTC, AlexMacsa commented on test/rc/TEST.nisx
> +            <LINKED Value="false"/>
Això es fa servir?

2023-03-03 15:04 UTC, iserramacsa commented on src/visitors/nisx/nisxwriter.cpp
> +}
corregit

2023-03-03 15:05 UTC, iserramacsa commented on src/builders/nisx/objects/fontparser.cpp
> +bool FontParser::VisitExit(const XMLElement& element)
corregit

2023-03-03 15:05 UTC, iserramacsa commented on include/dom/builders/nisxparser.hpp
> +		class NisxParser : public IDocumentParser
corregit

2023-03-03 15:05 UTC, iserramacsa commented on src/builders/nisx/objects/textparser.cpp
> +	if (!text || !_text) {
corregit

2023-03-03 15:05 UTC, iserramacsa commented on src/builders/nisx/objects/barcodeparser.cpp
> +	if (!barcode || !_barcode) {
corregit

2023-03-03 15:05 UTC, iserramacsa commented on src/builders/nisx/fieldsparser.cpp
> +				ObjectParser* parser {ObjectParsersFactory::Get(objectType->first, object)};
corregit

2023-03-03 15:06 UTC, merged